alias z="$ZDOTDIR"
alias d="$ZDOTDIR/zshrc.d"

alias zshenv="$EDITOR $ZDOTDIR/.zshenv"
alias zshrc="$EDITOR $ZDOTDIR/.zshrc"
alias plugins="$EDITOR $ZDOTDIR/.zsh_plugins.txt"
alias aliases="$EDITOR $ZSH_CUSTOM/*aliases.zsh"
alias scripts="$EDITOR $ZSH_CUSTOM/*scripts.zsh"
alias vars="$EDITOR $ZSH_CUSTOM/*vars.zsh"
alias paths="$EDITOR $ZSH_CUSTOM/*path.zsh"
alias it2vars="$EDITOR $ZSH_CUSTOM/*iterm2_variables.zsh"

alias cat="catx"
alias ls="lsx"
alias more="morex"
alias which="whence"

alias up="cd .."
alias f="yazi"
alias reload="exec zsh"
alias home="cd $HOME"
alias root="cd /"
alias img="imgcat"
alias path="echo $path"
alias python="python -q"
alias py="python"
alias spice="spicetify"
alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
alias keka="/Applications/Keka.app/Contents/MacOS/Keka --cli"
