#!/bin/zsh

base=$(basename "$@" 2> /dev/null || basename "$@" "$PWD")

if [[ "$base" == "/" ]]
then
	echo $(diskutil info / | awk -F': ' '/Volume Name/{gsub(/^ +| +$/,"",$2); print $2}')
else
	echo "$base"
fi

