#!/bin/zsh
##? TODO: Add description. Use ##? comments for funchelp docs.

###
### TODO: write your autoload function here.
### WARNING: Do not add a 'function edit() {}' wrapper for autoloads.
###

# vim: ft=zsh sw=2 ts=2 et

"$EDITOR" "$1"
