#!/bin/zsh
##? TODO: Add description. Use ##? comments for funchelp docs.

###
### TODO: write your autoload function here.
### WARNING: Do not add a 'function zdot() {}' wrapper for autoloads.
###

# vim: ft=zsh sw=2 ts=2 et

git_zdot() {
	git -C "$ZDOTDIR" "$@"
}

if [[ "$1" == "save" ]]
then
	git_zdot add -A && git_zdot commit --allow-empty --allow-empty-message -m ""
else
	git_zdot "$@"
fi
	
